spring.application.name=api-gateway
server.port=${API_GATEWAY_PORT:8080}

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://peer1:8761/eureka/,http://peer2:8762/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.registry-fetch-interval-seconds=5

spring.cloud.refresh.enabled=false

spring.cloud.gateway.server.webmvc.routes[0].id=rpg-event-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://rpg-event-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/events/**

management.endpoints.web.exposure.include=health,info,metrics,prometheus,gateway
