spring.application.name=eureka-server

server.port=8761

eureka.instance.hostname=peer1
eureka.instance.instance-id=${spring.application.name}:peer1:${server.port}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://peer2:8762/eureka/

eureka.client.registry-fetch-interval-seconds=5
eureka.server.response-cache-update-interval-ms=3000