server.port=8082

spring.cloud.function.definition=validateEventRules

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=1
eureka.instance.duration-in-seconds=2

eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.registry-fetch-interval-seconds=1

spring.cloud.loadbalancer.ribbon.enabled=false
