server.port=8081

client.rules-service.url=http://rpg-rules-function
client.graphql.url=http://rpg-narrative-service/graphql
app.clients.rules=remote
app.clients.narration=remote

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=1
eureka.instance.lease-expiration-duration-in-seconds=2

eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.registry-fetch-interval-seconds=1

spring.cloud.loadbalancer.ribbon.enabled=false
