spring.application.name=rpg-event-service
server.port=8081

client.rules-service.url=http://rpg-rules-function
client.graphql.url=http://rpg-narrative-service/graphql
app.clients.rules=remote
app.clients.narration=remote

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://peer1:8761/eureka/,http://peer2:8762/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.registry-fetch-interval-seconds=5

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.rulesFunction.register-health-indicator=true
resilience4j.circuitbreaker.instances.rulesFunction.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.rulesFunction.sliding-window-size=4
resilience4j.circuitbreaker.instances.rulesFunction.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.rulesFunction.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.rulesFunction.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.rulesFunction.permitted-number-of-calls-in-half-open-state=1

resilience4j.circuitbreaker.instances.narrativeService.register-health-indicator=true
resilience4j.circuitbreaker.instances.narrativeService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.narrativeService.sliding-window-size=4
resilience4j.circuitbreaker.instances.narrativeService.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.narrativeService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.narrativeService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.narrativeService.permitted-number-of-calls-in-half-open-state=1

resilience4j.timelimiter.instances.rulesFunction.timeout-duration=2s
resilience4j.timelimiter.instances.rulesFunction.cancel-running-future=true
resilience4j.timelimiter.instances.narrativeService.timeout-duration=2s
resilience4j.timelimiter.instances.narrativeService.cancel-running-future=true

resilience4j.retry.instances.rulesFunction.max-attempts=2
resilience4j.retry.instances.rulesFunction.wait-duration=300ms
resilience4j.retry.instances.narrativeService.max-attempts=2
resilience4j.retry.instances.narrativeService.wait-duration=300ms
